//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.
// Regenerate with: make generate
// (requires controller-gen installed; see Makefile for the pinned version)

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *ModelEndpoint) DeepCopyInto(out *ModelEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ModelEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ModelEndpoint) DeepCopy() *ModelEndpoint {
	if in == nil {
		return nil
	}
	out := new(ModelEndpoint)
	in.DeepCopyInto(out)
	return out
}

func (in *ModelEndpointList) DeepCopyInto(out *ModelEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ModelEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ModelEndpointList) DeepCopy() *ModelEndpointList {
	if in == nil {
		return nil
	}
	out := new(ModelEndpointList)
	in.DeepCopyInto(out)
	return out
}

func (in *ModelEndpointSpec) DeepCopyInto(out *ModelEndpointSpec) {
	*out = *in
	if in.MaxTokens != nil {
		x := *in.MaxTokens
		out.MaxTokens = &x
	}
	if in.CostBudget != nil {
		in, out := &in.CostBudget, &out.CostBudget
		*out = new(BudgetSpec)
		**out = **in
	}
	if in.RateLimit != nil {
		in, out := &in.RateLimit, &out.RateLimit
		*out = new(RateLimitSpec)
		**out = **in
	}
	if in.GuardrailPolicyRef != nil {
		x := *in.GuardrailPolicyRef
		out.GuardrailPolicyRef = &x
	}
}

func (in *ModelEndpointStatus) DeepCopyInto(out *ModelEndpointStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *PromptTemplate) DeepCopyInto(out *PromptTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *PromptTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PromptTemplate) DeepCopy() *PromptTemplate {
	if in == nil {
		return nil
	}
	out := new(PromptTemplate)
	in.DeepCopyInto(out)
	return out
}

func (in *PromptTemplateList) DeepCopyInto(out *PromptTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PromptTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *PromptTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PromptTemplateList) DeepCopy() *PromptTemplateList {
	if in == nil {
		return nil
	}
	out := new(PromptTemplateList)
	in.DeepCopyInto(out)
	return out
}

func (in *PromptTemplateSpec) DeepCopyInto(out *PromptTemplateSpec) {
	*out = *in
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make([]TemplateVariable, len(*in))
		copy(*out, *in)
	}
	out.ModelEndpointRef = in.ModelEndpointRef
	if in.MaxTokens != nil {
		x := *in.MaxTokens
		out.MaxTokens = &x
	}
}

func (in *PromptTemplateStatus) DeepCopyInto(out *PromptTemplateStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *GuardrailPolicy) DeepCopyInto(out *GuardrailPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *GuardrailPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GuardrailPolicy) DeepCopy() *GuardrailPolicy {
	if in == nil {
		return nil
	}
	out := new(GuardrailPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *GuardrailPolicyList) DeepCopyInto(out *GuardrailPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GuardrailPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *GuardrailPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GuardrailPolicyList) DeepCopy() *GuardrailPolicyList {
	if in == nil {
		return nil
	}
	out := new(GuardrailPolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *GuardrailPolicySpec) DeepCopyInto(out *GuardrailPolicySpec) {
	*out = *in
	if in.ContentPolicy != nil {
		in, out := &in.ContentPolicy, &out.ContentPolicy
		*out = new(ContentPolicyConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SensitiveInformationPolicy != nil {
		in, out := &in.SensitiveInformationPolicy, &out.SensitiveInformationPolicy
		*out = new(SensitiveInformationPolicyConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.TopicPolicy != nil {
		in, out := &in.TopicPolicy, &out.TopicPolicy
		*out = new(TopicPolicyConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.WordPolicy != nil {
		in, out := &in.WordPolicy, &out.WordPolicy
		*out = new(WordPolicyConfig)
		(*in).DeepCopyInto(*out)
	}
}

func (in *GuardrailPolicyStatus) DeepCopyInto(out *GuardrailPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ContentPolicyConfig) DeepCopyInto(out *ContentPolicyConfig) {
	*out = *in
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]ContentFilter, len(*in))
		copy(*out, *in)
	}
}

func (in *SensitiveInformationPolicyConfig) DeepCopyInto(out *SensitiveInformationPolicyConfig) {
	*out = *in
	if in.PIIEntities != nil {
		in, out := &in.PIIEntities, &out.PIIEntities
		*out = make([]PIIEntityConfig, len(*in))
		copy(*out, *in)
	}
}

func (in *TopicPolicyConfig) DeepCopyInto(out *TopicPolicyConfig) {
	*out = *in
	if in.Topics != nil {
		in, out := &in.Topics, &out.Topics
		*out = make([]DeniedTopic, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *DeniedTopic) DeepCopyInto(out *DeniedTopic) {
	*out = *in
	if in.Examples != nil {
		in, out := &in.Examples, &out.Examples
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *WordPolicyConfig) DeepCopyInto(out *WordPolicyConfig) {
	*out = *in
	if in.Words != nil {
		in, out := &in.Words, &out.Words
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ManagedWordLists != nil {
		in, out := &in.ManagedWordLists, &out.ManagedWordLists
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *BudgetSpec) DeepCopyInto(out *BudgetSpec)             { *out = *in }
func (in *RateLimitSpec) DeepCopyInto(out *RateLimitSpec)       { *out = *in }
func (in *ModelEndpointRef) DeepCopyInto(out *ModelEndpointRef) { *out = *in }
func (in *TemplateVariable) DeepCopyInto(out *TemplateVariable) { *out = *in }
func (in *ContentFilter) DeepCopyInto(out *ContentFilter)       { *out = *in }
func (in *PIIEntityConfig) DeepCopyInto(out *PIIEntityConfig)   { *out = *in }
